/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import pojos.Medicos;
import pojos.Paciente;
import pojos.Consulta;
import java.util.ArrayList;
        

/**
 * Tela de login do sistema:
 *  Seleciona o perfil de acesso
 * @author cintiasb
 */
public class TelaLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaLogin.class.getName());

    /**
     * Creates new form MenuPrincipal
     */
    public TelaLogin() {
        initComponents();
        setLocationRelativeTo(null); // centraliza na tela do computador

        // médico fixo igual ao projeto original
        pojos.Medicos medico = new pojos.Medicos("Dr. Carlos Silva", "CRM-12345", "Clínico Geral");
        lstMedicos.add(medico);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        Secretaria = new javax.swing.JButton();
        Medico = new javax.swing.JButton();
        Subtitulo = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clínica Saude & Cia");
        setBackground(new java.awt.Color(153, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(null);
        setMinimumSize(null);
        setName(""); // NOI18N

        Titulo.setBackground(new java.awt.Color(255, 255, 255));
        Titulo.setFont(new java.awt.Font("Adwaita Sans", 1, 22)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Clínica Saúde & Cia");
        Titulo.setToolTipText("");
        Titulo.setAlignmentY(0.0F);
        Titulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Titulo.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Titulo.setFocusCycleRoot(true);
        Titulo.setFocusable(false);
        Titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Titulo.setMaximumSize(null);
        Titulo.setMinimumSize(null);
        Titulo.setName(""); // NOI18N
        Titulo.setPreferredSize(null);

        Secretaria.setText("Secretária");
        Secretaria.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Secretaria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Secretaria.setFocusCycleRoot(true);
        Secretaria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Secretaria.setName(""); // NOI18N
        Secretaria.addActionListener(this::SecretariaActionPerformed);

        Medico.setText("Doutor");
        Medico.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Medico.setFocusCycleRoot(true);
        Medico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Medico.setName(""); // NOI18N
        Medico.addActionListener(this::MedicoActionPerformed);

        Subtitulo.setFont(new java.awt.Font("Adwaita Sans", 1, 14)); // NOI18N
        Subtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Subtitulo.setText("Selecione o perfil de acesso:");
        Subtitulo.setFocusCycleRoot(true);
        Subtitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Subtitulo.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Medico, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Secretaria, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Subtitulo)
                    .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Medico, Secretaria});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Subtitulo)
                .addGap(59, 59, 59)
                .addComponent(Secretaria, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(Medico, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Medico, Secretaria});

        Titulo.getAccessibleContext().setAccessibleName("");
        Secretaria.getAccessibleContext().setAccessibleName("");
        Secretaria.getAccessibleContext().setAccessibleDescription("");
        Medico.getAccessibleContext().setAccessibleName("");
        Medico.getAccessibleContext().setAccessibleDescription("");
        Subtitulo.getAccessibleContext().setAccessibleName("");
        Subtitulo.getAccessibleContext().setAccessibleDescription("");

        getAccessibleContext().setAccessibleName("");
        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SecretariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecretariaActionPerformed
        // TODO add your handling code here:
        new TelaMenuSecretaria(lstPacientes, lstConsultas, lstMedicos).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_SecretariaActionPerformed

    private void MedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Medico;
    private javax.swing.JButton Secretaria;
    private javax.swing.JLabel Subtitulo;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
